# Site settings
theme: jekyll-theme-easy-wedding
title: Nainika & Charles
email: cwlgadd@gmail.com
description: "We're getting married and can't wait to celebrate with you!"
url: https://cwlgadd.github.io # Be sure to include http:// or https://
baseurl: "/wedding-site"

collections:
  stories:
    sort_by: order
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      type: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml
